### ISSUE TITLE
Getting events to display properly in another timezone

### ISSUE THREAD

**Issue by bslade** [chadn/mapfilter#1]
Just in case anyone else has this problem, here are the lines of code I modified in js/cnMapFilter.js to get event times to display properly in Washington DC as opposed to Chicago (for bikesfortheworld.org):
### old

```
ctz' : 'America/Chicago',
```
### new

```
// 'ctz' : 'America/Chicago',
```
### old

```
return s + "-08:00"; // chicago offset
```
### new

```
// was -8
return s + "-07:00"; // chicago offset
```

**Comment by chadn** [comment]
as of 2011-9-21, gcm defaults to browser’s timezone.  Adding tz=cal to URL will use calendar’s timezone.  Ex: http://chadnorwood.com/gcm/?tz=cal&u=https://www.google.com/calendar/feeds/dnr6osjdrtn4fqpf70ep8ck1rc%40group.calendar.google.com/public/basic

http://chadnorwood.com/projects/gcm/#urlOptions
