### ISSUE TITLE
Mapfilter Browser behavior - FireFox 12, iPAD2, IE9, IE8

### ISSUE THREAD

**Issue by zignjny** [chadn/mapfilter#4]
Hi, I downloaded the latest code  [chadn-mapfilter-0.3-0-g7dc49a8]  on May 25, 2012. This is a great application that I am styling to incorporate into our website.  Thanks for all of your hard work! i thought it might help if I listed some observations from various browsers when th eincluded 'index.html' is run from the examples ....
1. Firefox v12.0 ... right hand slider does not move. Left hand slider moves once either by dragging or clicking the 'path' between the two ends. Then neither slider responds until the map is cleared back to all events shown.
2. iPAD2: 
   2a:slider movement is limited when dragging with finger. either left of right slider only moves a few pixels til dragged again. Touching the 'path' between moves either slider as expected.
   2b: Touching the NAME entry in the table does nothing. It does not move to the selected event. Note, touching an event marker DOES highlight the corresponding name entry in the table and does popup the info window for the event. Note:Zoom To and Directions appear to work on the iPAD.
   2c: touching the Event Details link in the table brings up a Google Calendar sign in screen instead of going to the public event detail.
3. IE 9.0 ....All functions are working nicely.
4. IE 8.0 ....The right slider does not function. The left slider behave correctly. All other functions are working nicely.

Thanks again. i wil be checking in to see the progress.
Regards,
Ken Z

**Comment by chadn** [comment]
Thanks for the feedback. I fixed the sliders on firefox 12 and IE - basically switched to latest jqueryUI code which has "overlapping sliders".  See changelog for more.

I didn't even test in the iPad till now, thanks for looking into that.  I can already tell there is several issues with the iPad, I will have to revisit iPad support at a later time.
